xmllint pre-commit check configuration file
lsst-ts/ts_xml pull request #460
Opened 2021-06-15 11:21 UTC by pkubanek

2021-06-15 18:31 UTC, rbovill requested changes
A couple of minor, but possibly significant, changes requested.

2021-06-15 18:31 UTC, rbovill commented on sal_interfaces/MTM1M3/MTM1M3_Commands.xml
> +        reference position specified in configuration file. New mirror position
Position the mirror **relative to the reference** position specified in **the** configuration file

2021-06-15 18:31 UTC, rbovill commented on sal_interfaces/MTM1M3/MTM1M3_Commands.xml
> +        xRotation, yRotation and zRotation.
will be **rotated** by

2021-06-16 15:33 UTC, pkubanek commented
Addressed Rob's suggestions.

2021-06-16 22:05 UTC, rbovill approved these changes
LGtM

2021-06-16 23:14 UTC, merged