Adding ASHeaderService CSC, HeaderService for the All Sky Camera
lsst-ts/ts_xml pull request #477
Opened 2021-08-17 17:34 UTC by menanteau

2021-08-23 19:41 UTC, mareuter commented
The main check failed since one of the unit test files was not updated. Please see the _Test Utilities_ section of the README in https://github.com/lsst-ts/ts_xml.

2021-08-25 14:48 UTC, menanteau commented
Added ASHeaderService to testutils.py

2021-08-25 15:46 UTC, tribeiro requested changes
Sorry @menanteau , as we've been discussing in slack. I would like to propose we rename this CSC GCHeaderService (GC - Generic Camera) and make it an indexed component to match that of the GenericCamera.

2021-08-31 20:41 UTC, menanteau commented
@mareuter  and @tribeiro I have renamed ASHeaderService to GCHeaderService as discussed.

2021-08-31 22:13 UTC, tribeiro commented on sal_interfaces/SALSubsystems.xml
> +    <IndexEnumeration>no</IndexEnumeration>
This need to be:

```
<IndexEnumeration>any</IndexEnumeration>
```

2021-09-01 01:17 UTC, menanteau commented on sal_interfaces/SALSubsystems.xml
> +    <IndexEnumeration>no</IndexEnumeration>
Fixed

2021-09-01 13:43 UTC, tribeiro commented on sal_interfaces/SALSubsystems.xml
> +    <IndexEnumeration>no</IndexEnumeration>
thank you so much!

2021-09-01 13:43 UTC, tribeiro approved these changes
Thanks for the updates!

2021-09-02 15:18 UTC, mareuter approved these changes
This is good to merge.

2021-09-02 15:20 UTC, merged