Tickets/dm36802 - Convert ts_xml to pyproject.toml
lsst-ts/ts_xml pull request #636
Opened 2022-11-02 18:08 UTC by rbovill

2022-11-02 18:38 UTC, tribeiro commented on conda/meta.yaml
> +  name: ts-integrationtests
This should probably be `ts-xml`

2022-11-02 18:38 UTC, tribeiro commented on conda/meta.yaml
> +  script: python -m pip install --ignore-installed -e .
Take a look at [this confluence page](https://confluence.lsstcorp.org/x/0Il-Cw), it has some updates to the conda recipe to make them forward compatible with different versions of python..

2022-11-02 18:39 UTC, wvreeven requested changes
Sorry for pushing back on the changes made to one python file. I really don't think those are necessary and I fear they will still break the way the Makefile in the doc directory has been implemented.

2022-11-02 18:39 UTC, wvreeven commented on python/lsst/ts/xml/generate_csv_table.py
> +    outpath = utils.get_pkg_root() / "subsystemData.csv"
I still very strongly think that the `subsystemData.csv` file should not be moved from the `doc` directory. Are you sure that this is absolutely necessary? I don't think that any changes to the `generate_csv_table.py` file are necessary, including the change to line 141.

2022-11-02 18:48 UTC, r-owen approved these changes
I have one suggested change and I'll leave it to you and @wvreeven to decide what to do about that one generated file.

2022-11-02 19:57 UTC, r-owen approved these changes
Looks fine to me

2022-11-02 19:57 UTC, r-owen commented on setup.cfg
> +  doc/conf.py,
I gently suggest making doc/conf.py pass flake8. It makes more a much more pleasant experience when editing the file in some editors. It does require some # noqa entries. Here is an example from ts_utils:
```
from documenteer.conf.pipelinespkg import *  # type: ignore # noqa
import lsst.ts.utils  # noqa

project = "ts_utils"
html_theme_options["logotext"] = project  # type: ignore # noqa
html_title = project
html_short_title = project
# Avoid warning: Could not find tag file _doxygen/doxygen.tag
doxylink = {}  # type: ignore
```

2022-11-02 21:06 UTC, tribeiro approved these changes
Looks good! I did left a few more comments on the conda recipe! please, take a look before merging. The current recipe won't build properly because it is missing a test dependency and it won't run properly because it is missing some run dependencies.

2022-11-02 21:06 UTC, tribeiro commented on conda/meta.yaml
> +    - astropy
Please, include 

```
    - ts-conda-build =0.3
```

here.

2022-11-02 21:06 UTC, tribeiro commented on conda/meta.yaml
> +    - python {{ python }}
I think you also need `astropy` and `lxml` as run dependencies (but no `ts-conda-build`, which is only a test dependency).

2022-11-03 12:00 UTC, wvreeven approved these changes
Thanks for the additional changes. Looks good to me now.

2022-11-03 15:10 UTC, merged