updating tunable laser states
lsst-ts/ts_xml pull request #846
Opened 2024-05-17 20:07 UTC by parfa30

Associated with https://github.com/lsst-ts/ts_TunableLaser/pull/52

2024-05-20 16:48 UTC, couger01 requested changes
You need to update the enumeration here as well https://github.com/lsst-ts/ts_xml/blob/6b20a718d370e90034a02b34f6624f41a3a88269/python/lsst/ts/xml/data/sal_interfaces/TunableLaser/TunableLaser_Events.xml#L4. Also you need to correct the name of the news fragment but otherwise looks good.

2024-05-20 16:48 UTC, couger01 commented on doc/news/DM-44083.misc.rst
Needs to be under interface_changes folder and using the name DM-44083.tunablelaser.rst.

2024-05-20 18:02 UTC, parfa30 commented on doc/news/DM-44083.misc.rst
I hadn't realized that. Thanks! I moved and renamed the file.

2024-05-21 14:38 UTC, couger01 requested changes
Can you remove the old news fragment otherwise looks real good to me.

2024-05-21 14:38 UTC, couger01 commented on doc/news/DM-44083.misc.rst
It seems like the old file wasn't removed, could you remove this one please?

2024-05-21 15:12 UTC, parfa30 commented
Oh shoot! I thought it was removed. It should be now.

2024-05-22 16:55 UTC, couger01 approved these changes
LGTM, make sure to rebase on latest develop and squash the commits please.

2024-05-22 21:20 UTC, merged