updated grating enumeration
lsst-ts/ts_xml pull request #890
Opened 2024-08-14 16:18 UTC by parfa30

This should be merged as part of xml-23. Also, when merged, will need to change some of the scripts so that they align with the updated configuration.

2024-08-21 14:36 UTC, couger01 requested changes
One requested change.

2024-08-21 14:36 UTC, couger01 commented on doc/news/DM-45475.misc.rst
I would remove the part about Windows 10 and simply leave it as updating the grating enumeration.

2024-08-21 20:05 UTC, couger01 approved these changes
LGTM.

2024-08-21 20:06 UTC, couger01 requested changes
Change the news fragment to use Electrometer section not misc.

2024-08-21 20:58 UTC, parfa30 commented
I don't know what you mean. Do you mean change the name of the news fragment to be DM-45475.Electrometer.rst? This is for the monochromator.

2024-08-22 18:16 UTC, couger01 approved these changes
LGTM.

2024-08-22 18:21 UTC, merged