Add temperature attribute to ATAOS applyCorrection
lsst-ts/ts_xml pull request #905
Opened 2024-09-08 19:56 UTC by gmegh

2024-09-08 21:33 UTC, tribeiro requested changes
Please, add temperature attributes to all the relevant events e.g.: 

- https://github.com/lsst-ts/ts_xml/blob/a16574f2a257c25557144337a94d9ba50605b017/python/lsst/ts/xml/data/sal_interfaces/ATAOS/ATAOS_Events.xml#L66
- https://github.com/lsst-ts/ts_xml/blob/a16574f2a257c25557144337a94d9ba50605b017/python/lsst/ts/xml/data/sal_interfaces/ATAOS/ATAOS_Events.xml#L92
- https://github.com/lsst-ts/ts_xml/blob/a16574f2a257c25557144337a94d9ba50605b017/python/lsst/ts/xml/data/sal_interfaces/ATAOS/ATAOS_Events.xml#L118
- https://github.com/lsst-ts/ts_xml/blob/a16574f2a257c25557144337a94d9ba50605b017/python/lsst/ts/xml/data/sal_interfaces/ATAOS/ATAOS_Events.xml#L144
- https://github.com/lsst-ts/ts_xml/blob/a16574f2a257c25557144337a94d9ba50605b017/python/lsst/ts/xml/data/sal_interfaces/ATAOS/ATAOS_Events.xml#L170
- https://github.com/lsst-ts/ts_xml/blob/a16574f2a257c25557144337a94d9ba50605b017/python/lsst/ts/xml/data/sal_interfaces/ATAOS/ATAOS_Events.xml#L231
- https://github.com/lsst-ts/ts_xml/blob/a16574f2a257c25557144337a94d9ba50605b017/python/lsst/ts/xml/data/sal_interfaces/ATAOS/ATAOS_Events.xml#L292
- https://github.com/lsst-ts/ts_xml/blob/a16574f2a257c25557144337a94d9ba50605b017/python/lsst/ts/xml/data/sal_interfaces/ATAOS/ATAOS_Events.xml#L318

2024-09-08 21:40 UTC, gmegh commented
I think I have added them to all of the events

2024-09-09 18:47 UTC, tribeiro commented on doc/news/interface_changes/DM-46190.ataos.rst
> +Add temperature attribute to ATAOS_command_applyCorrection.
Please, mention that you are also adding it to the events.

2024-09-09 20:15 UTC, tribeiro approved these changes
looks good

2024-09-23 21:16 UTC, merged